version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'ci: '

  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore: '
